### ISSUE TITLE
Lollipop Unable to start PushIOGCMIntentService

### ISSUE THREAD

**Issue by obec** [pushio/PushIOManager_Android#2]
After upgrading from 2.10.7 to 2.11.0 the PushIOGCMIntentService is unable to start on Lollipop devices. Amazon and pre-Lollipop devices still work.

I followed the steps here to add the new permission: https://docs.pushio.com/Android/Updation_Guide

Google Play Services base, ads, and play modules were already included in the project. I have also tried the full Google Play Services dependency to see if that was the issue.

> 02-16 15:56:37.181  28189-28189/<package> D/pushio﹕ Push IO Manager - version: 2.11.0
> 02-16 15:56:37.186  28189-28189/<package> D/pushio﹕ Detecting notification service...
> 02-16 15:56:37.197  28189-28189/<package> D/pushio﹕ Google Play Services found, using GCM for notification service.
> 02-16 15:56:37.199  28189-28189/<package> D/pushio﹕ Registering device with 'GCM' servers...
> 02-16 15:56:39.710  28189-28189/<package> E/pushio﹕ Unable to start PushIOGCMIntentService
> 02-16 15:56:52.907  28189-28189/<package> D/pushio﹕ Registering device with 'GCM' servers...
> 02-16 15:56:53.447  28189-28189/<package> E/pushio﹕ Unable to start PushIOGCMIntentService

Please let me know what additional information would be useful.

**Comment by HiroProt** [comment]
Hi Caleb, we're looking into it and will get back to you shortly.
