### ISSUE TITLE
Emulator crash on virtual devices without required Google Play Services version

### ISSUE THREAD

**Issue by troyjperales** [pushio/PushIOManager_Android#3]
I am seeing the following crash when I attempt to use an emulator. The emulator includes Google APIs and an added Google account.

>      Caused by: java.lang.NullPointerException
>            at com.pushio.manager.PushIOManager.scheduleRegistration(PushIOManager.java:193)
>            at com.pushio.manager.PushIOManager.registerCategories(PushIOManager.java:354)
>            at com.pushio.manager.PushIOManager.registerCategory(PushIOManager.java:329)

Prior to this I am seeing the following:

>      D/pushio﹕ Push IO Manager - version: 2.11.1
>      D/pushio﹕ Detecting notification service...
>      W/pushio﹕ GCM not found. Trying ADM.
>      W/pushio﹕ ADM not found. Device supports no known notification services.
>      D/pushioconfig﹕ Error reading local pushio_config_adm.json. Ensure that you have downloaded
>            the pushio_config_adm.json from manage.push.io, and include it in your application
>            assets.
>      java.io.FileNotFoundException: pushio_config_adm.json
>            at android.content.res.AssetManager.openAsset(Native Method)
>            at android.content.res.AssetManager.open(AssetManager.java:315)
>            at android.content.res.AssetManager.open(AssetManager.java:289)
>            at com.pushio.manager.PushIOConfig.createPushIOConfigFromAssets(PushIOConfig.java:137)
>            at com.pushio.manager.PushIOManager.<init>(PushIOManager.java:101)
>            at com.pushio.manager.PushIOManager.getInstance(PushIOManager.java:75)
>            at com.foxnews.android.FNApplication.onCreate(FNApplication.java:107)
>            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
>            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
>            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
>            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
>            at android.os.Handler.dispatchMessage(Handler.java:99)
>            at android.os.Looper.loop(Looper.java:137)
>            at android.app.ActivityThread.main(ActivityThread.java:5041)
>            at java.lang.reflect.Method.invokeNative(Native Method)
>            at java.lang.reflect.Method.invoke(Method.java:511)
>            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
>            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
>            at dalvik.system.NativeStart.main(Native Method)

**Comment by HiroProt** [comment]
Hi Troy,

What OS version are you emulating?

Thanks,
Martin

**Comment by troyjperales** [comment]
I have tried with API version 14 and 17 so far.

**Comment by HiroProt** [comment]
Do you see a "Google Play services out of date" message in your log?

**Comment by troyjperales** [comment]
I do.
>      W/GooglePlayServicesUtil﹕ Google Play services out of date.  Requires 6587000 but found 3136130

**Comment by HiroProt** [comment]
You'll need to update your AVD via the SDK Manager, so that you have an emulator with a current Google Play Services version.

**Comment by troyjperales** [comment]
So the expected implementation is to force the user to update to the necessary GPS version via  GooglePlayServicesUtil.getErrorDialog(); otherwise, disable Push IO altogether?

**Comment by HiroProt** [comment]
We're working on an SDK update that will automatically address this, but until that's released (no ETA yet), we recommend only calling ensureRegistration if the GPS is up-to-date.

**Comment by troyjperales** [comment]
Thanks @HiroProt . I'll leave it to you to close this or not.

**Comment by HiroProt** [comment]
We'll close it out once the SDK has been updated with a fix. Thanks for the report, appreciate it :)

**Comment by neerhaj** [comment]
Fixed. 6093c8bed4dd9ce1bd52bcea4fa7074805c3be85
