### ISSUE TITLE
Device not registering

### ISSUE THREAD

**Issue by renato-almeida** [pushio/PushIOManager_Android#5]
Hi there, 

According to your **Step-by-Step Setup Instructions**, calling **.ensureRegistration()** also registers for Broadcast Push Notifications, but that is not happening.

On my Application onCreate method I'm calling
```java
PushIOManager pushIOManager = PushIOManager.getInstance(this);
pushIOManager.ensureRegistration();
```

With the output:
````
D/pushio﹕ Push IO Manager - version: 2.13.2
D/pushio﹕ LEP PushIOLocalEventProcessor loaded
D/pushio﹕ PH registerPushMessageListener
D/pushio﹕ EM registerPushIOEventListener
D/pushio﹕ Detecting notification service...
D/pushio﹕ Google Play Services found, using GCM for notification service.
```
By the output, I believe that it didn't registered.
And if I send a push notification, nothing happens.

but if I call registerCategory after ensureRegistration
```java
pushIOManager.ensureRegistration();
pushIOManager.registerCategory("test");
```

Then I get the output:
```
D/pushio﹕ Push IO Manager - version: 2.13.2
D/pushio﹕ LEP PushIOLocalEventProcessor loaded
D/pushio﹕ PH registerPushMessageListener
D/pushio﹕ EM registerPushIOEventListener
D/pushio﹕ Detecting notification service...
D/pushio﹕ Google Play Services found, using GCM for notification service.
D/pushio﹕ mRegisteringNotificationPreferences: null,mScheduledNotificationPreferences: null
D/pushio﹕ Get All PushIO Preferences
D/pushio﹕ mPushIOPersistenceManagerMap: 0
D/pushio﹕ Scheduling a new registration in 15 seconds
D/pushio﹕ Starting registration...
D/pushio﹕ Register - Request String: ...
D/pushio﹕ Registration with push.io servers successful!
```

And then if I send broadcast push, the device receives the notification.

Am I doing anything wrong?

**Comment by neerhaj** [comment]
Hi,

Are you still seeing this issue?

**Comment by renato-almeida** [comment]
@neerhaj yes, it's still happening

**Comment by neerhaj** [comment]
@renato-almeida Is the first log posted above the complete log? If not, could you share the entire log?

**Comment by renato-almeida** [comment]
I was filtering by the tag "push", do you use another log tag?

**Comment by neerhaj** [comment]
We use "pushio", but "push" would give same results.

**Comment by renato-almeida** [comment]
So thats all the log I have

**Comment by neerhaj** [comment]
@renato-almeida we have identified the problem and are working on a fix. We'll let you know once we release the fix.

**Comment by renato-almeida** [comment]
@neerhaj great!

**Comment by neerhaj** [comment]
@renato-almeida Just to give you an overview of the issue here, the SDK registers for push notifications on the first run, but it has a wait time of 5 hrs before attempting registration again. So if the app is re-launched or restarted, the registration does not go through. We are working to fix this.

As a temporary workaround, you can either clear app data before launcing the app or make a call to `PushIOManager.registerCategory()`, which should initiate the registration as you posted earlier.

**Comment by renato-almeida** [comment]
@neerhaj thanks.
any ETA for the release of the version with the fix?

**Comment by neerhaj** [comment]
@renato-almeida We have a release planned for early next week and this fix should be part that release. We'll keep you updated.

**Comment by neerhaj** [comment]
@renato-almeida We are still working on the fix for this issue. We expect this fix to be part of the release going out next week.

We'll keep you updated.

**Comment by neerhaj** [comment]
@renato-almeida New version of SDK is released. Kindly check it out and let us know.

**Comment by renato-almeida** [comment]
@neerhaj all good, great work.
