### ISSUE TITLE
Not able to receive push notification

### ISSUE THREAD

**Issue by zatokar1** [pushio/PushIOManager_Android#7]
I made an android app according to this guide: http://docs.oracle.com/cloud/latest/marketingcs_gs/OMCFA/android/step-by-step/

I have used standard xml configuration. I am able to register and this is my log:

D/pushio﹕ Google Play Services found, using GCM for notification service.
D/pushio﹕ mRegisteringNotificationPreferences: null,mScheduledNotificationPreferences: null
D/pushio﹕ Get All PushIO Preferences
D/pushio﹕ mPushIOPersistenceManagerMap: 0
D/pushio﹕ Scheduling a new registration in 15 seconds
I/Broadcast registered﹕ true
D/Activity﹕ #1 setTransGradationModeColor false
D/OpenGLRenderer﹕ Enabling debug mode 0
D/pushio﹕ Starting registration...
D/pushio﹕ Register - Request String: dt=xxx
D/pushio﹕ Registration with push.io servers successful!

The problem is, I never receive any notification and also the PushIO manager from which I am pushing doesn't show any number above 'Sent'. See picture:
![pushio issue](https://cloud.githubusercontent.com/assets/6918472/12419304/7a8f7b6a-beb5-11e5-959f-6f0454a773b5.PNG)

**Comment by neerhaj** [comment]
Hi,
Kindly use [My Oracle Support] (http://support.oracle.com/) for reporting issues related to the PushIO SDK.
